version: '3.8'

services:
  video-audio-tools:
    build: .
    ports:
      - "8085:8000"
    networks:
      - runtipi_tipi_main_network
    restart: unless-stopped

networks:
  runtipi_tipi_main_network:
    external: true